### ISSUE TITLE
required for the more data

### ISSUE THREAD

**Issue by eric-hang** [ogencoglu/causal_twitter_modeling_covid19#1]
Could you please upload more data?
I'm trying to improve your model and I'm going to test other causal discovery method such as DAG-GNN.
I may need more data to improve the performance.

Thanks a lot!

**Comment by ogencoglu** [comment]
Hi,
I am not allowed to upload any tweets due to Twitter's legal policies. 

And for covid data, you can find more recent stats here: https://github.com/CSSEGISandData/COVID-19
